name: Aggiornamento Annunci

on:
  schedule:
    - cron: '0 3 * * *'  # ogni notte alle 3
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout del codice
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Installa dipendenze
        run: npm install

      - name: Genera index.html
        run: node build140425.js

      - name: Commit e push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add index.html
          git commit -m "Aggiornamento notturno automatico"
          git push
